stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - config/path_config.py
    outs:
      - artifacts/ingested_data

  data_processing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - config/path_config.py
    outs:
      - artifacts/processed_data

  feature_engineering:
    cmd: python src/future_selection.py
    deps:
      - src/future_selection.py
      - config/path_config.py
      - utils/common.py
    outs:
      - artifacts/engineered_data

  model_training:
    cmd: python src/model_training.py
    deps:
      - src/model_training.py
      - config/path_config.py
    outs:
      - artifacts/models



